# Generated by Django 3.1.5 on 2021-01-18 23:30

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django.contrib.postgres.fields.citext.CIEmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', django.contrib.postgres.fields.citext.CICharField(max_length=50, unique=True)),
                ('first_name', django.contrib.postgres.fields.citext.CICharField(max_length=100)),
                ('last_name', django.contrib.postgres.fields.citext.CICharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('photo', models.ImageField(default='user_images/avatar.png', upload_to='user_images')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
