// user types
export const OPEN_SIGNUP = "OPEN_SIGNUP";
export const CLOSE_SIGNUP = "CLOSE_SIGNUP";
export const OPEN_LOGIN = "OPEN_LOGIN";
export const CLOSE_LOGIN = "CLOSE_LOGIN";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const LOGOUT = "LOGOUT";
export const OPEN_FORGOT_PASSWORD = "OPEN_FORGOT_PASSWORD";
export const CLOSE_FORGOT_PASSWORD = "CLOSE_FORGOT_PASSWORD";
export const OPEN_RESEND_ACTIVATION = "OPEN_RESEND_ACTIVATION";
export const CLOSE_RESEND_ACTIVATION = "CLOSE_RESEND_ACTIVATION";
export const OPEN_PASSWORD_RESET_CONFIRM = "OPEN_PASSWORD_RESET_CONFIRM";
export const CLOSE_PASSWORD_RESET_CONFIRM = "CLOSE_PASSWORD_RESET_CONFIRM";
export const OPEN_CHANGE_PASSWORD = "OPEN_CHANGE_PASSWORD";
export const CLOSE_CHANGE_PASSWORD = "CLOSE_CHANGE_PASSWORD";

// shared types
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
